apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
spec:
  selector:
    matchLabels:
      app: nodeapp
replicas: 2
template:
  metadata:
    labels:
      app: nodeapp 
    spec:
      containers:
      - name: nodeserver
        image: midguar/nodeapp:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: nodeapp 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110
